class FormatColor(object):
    BLACK = '§0'
    DEEP_BLUE = '§1'
    DEEP_GREEN = '§2'
    LAKE_BLUE = '§3'
    DEEP_RED = '§4'
    PURPLE = '§5'
    GOLD = '§6'
    GREY = '§7'
    DEEP_GREY = '§8'
    BLUE = '§9'
    GREEN = '§a'
    AQUA = '§b'
    RED = '§c'
    LIGHT_PURPLE = '§d'
    YELLOW = '§e'
    WHITE = '§f'